---
title: "grade_analysis"
author: "Disem Sula"
format: html
editor: visual
---

```{r}
#| echo: false
#| message: false
here::i_am("grade_analysis_LAB.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
```

## Grade analisys LAB

### Question 1

```{r}
#| echo: false
#| message: false
grades <- vroom(here("grades.csv"))
```

### Question 2

```{r}
grades |>
  summarise(min(Exam, na.rm = TRUE), max(Exam, na.rm = TRUE), mean(Exam,na.rm = TRUE),n()) |>
  knitr::kable()
```

### Question 3

```{r}
missingstud<-sum(is.na(grades$Exam))
```

There is a total of `r missingstud` students who passed the test

### Question 4

```{r}
ggplot(grades, aes(x=Exam))+
  geom_histogram(binwidth=1.5, na.rm=TRUE) +
  labs(x="Exam grades", y= "count")
```

### Question 5

```{r}
grades |>
  group_by(Group) |>
  summarise(N=n()) |>
  knitr::kable()
```

### Question 6

```{r}
group_counts <- grades |>
  group_by(Group) |>
  summarise(N = n())

ggplot(group_counts, aes(x = Group, y = N)) +
  geom_bar(stat = "identity") +
  labs(x = "Group", y = "Number of Students") +
  ggtitle("Number of Students in Each Group") +
  theme(axis.text.x = element_text(angle = 90))
```

### Question 7

```{r}
ggplot(grades, aes(x = Group, y = Exam)) + 
  geom_boxplot() +
  labs(x="groups", y="grade")
```
